# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json* ./
RUN npm install --production --ignore-scripts

# Copy source
COPY src ./src
COPY .env* ./

# Use non-root user (optional)
RUN addgroup -S appgroup && adduser -S appuser -G appgroup
USER appuser

# Entry point
ENTRYPOINT ["node", "src/index.js"]
